/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/public/header.vue')['default']
    Integral: typeof import('./src/components/user/integral.vue')['default']
    IntegralAdded: typeof import('./src/components/admin/integralAdded.vue')['default']
    IntegralStatistics: typeof import('./src/components/admin/integralStatistics.vue')['default']
    IntegralUpdate: typeof import('./src/components/admin/integralUpdate.vue')['default']
    NutAnimate: typeof import('@nutui/nutui-taro')['Animate']
    NutAvatar: typeof import('@nutui/nutui-taro')['Avatar']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCheckbox: typeof import('@nutui/nutui-taro')['Checkbox']
    NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutInputNumber: typeof import('@nutui/nutui-taro')['InputNumber']
    NutNotify: typeof import('@nutui/nutui-taro')['Notify']
    NutTable: typeof import('@nutui/nutui-taro')['Table']
    NutTabPane: typeof import('@nutui/nutui-taro')['TabPane']
    NutTabs: typeof import('@nutui/nutui-taro')['Tabs']
    Piano: typeof import('./src/components/user/piano.vue')['default']
    PianoAdded: typeof import('./src/components/admin/pianoAdded.vue')['default']
    PianoExport: typeof import('./src/components/admin/pianoExport.vue')['default']
    PianoStatistics: typeof import('./src/components/admin/pianoStatistics.vue')['default']
    PianoUpdate: typeof import('./src/components/admin/pianoUpdate.vue')['default']
  }
}
